# GitHub Actions: .github/workflows/deploy.yml
# --------------------------------------------
# Place in `.github/workflows/deploy.yml`

# name: Deploy Application
# on:
#   push:
#     branches: [main]
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       - name: Login to DockerHub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build and push frontend
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/sp-web2-frontend:latest -f frontend/Dockerfile .
#           docker push ${{ secrets.DOCKER_USERNAME }}/sp-web2-frontend:latest
#       - name: Build and push backend
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/sp-web2-backend:latest -f backend/Dockerfile .
#           docker push ${{ secrets.DOCKER_USERNAME }}/sp-web2-backend:latest
